import { useEffect, useState } from 'react'
import { PageHeader } from '../../components/ui/PageHeader.jsx'
import { Badge, Card, CardBody, CardHeader, Spinner, StatusBadge } from '../../components/ui/primitives.jsx'
import { DataTable } from '../../components/ui/DataTable.jsx'
import { monitoringService, policyService, toList, withFallback } from '../../services/index.js'
import { BookCheck, History, ScrollText } from 'lucide-react'

export default function BusinessRules() {
  const [rules, setRules] = useState([]); const [logs, setLogs] = useState([]); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(true)
  useEffect(() => { const load = async () => { const [ruleResult, logResult] = await Promise.all([withFallback(() => policyService.list()), withFallback(() => monitoringService.logs())]); const ruleRows = toList(ruleResult.data); setRules(ruleRows); setLogs(toList(logResult.data)); setSelected(ruleRows[0] || null); setLoading(false) }; load() }, [])
  if (loading) return <div className="flex justify-center rounded-2xl border bg-white py-20"><Spinner className="h-7 w-7" /></div>
  const auditRows = logs.slice(0, 8).map((log, index) => ({ id: log.id || index, actor: log.actor || log.user || 'System', timestamp: log.timestamp || log.time || '—', oldValue: log.oldValue || log.service || '—', newValue: log.newValue || log.message || '—', decision: log.decision || log.level || 'Recorded' }))
  return <div><PageHeader breadcrumb="System Administration · 3.11.2" title="Maintain Business Rules and Audit Traceability" subtitle="Review active business rules, definitions, version history, and recorded system decisions." /><div className="grid items-start gap-6 xl:grid-cols-5"><section className="min-w-0 xl:col-span-2"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Business Rule List</h2><p className="text-xs text-slate-500">Select a rule to inspect its definition.</p></div><Badge tone="slate">{rules.length} rules</Badge></div><DataTable dense rows={rules} onRowClick={setSelected} empty={{ title: 'No business rules found' }} columns={[{ key: 'id', header: 'Rule ID', render: (row) => <span className="font-mono text-xs">{row.code || row.id}</span> }, { key: 'category', header: 'Module' }, { key: 'status', header: 'Status', render: (row) => <StatusBadge status={row.status || 'Active'} /> }, { key: 'effective', header: 'Effective', render: (row) => row.updatedDate || row.updated || 'Current' }]} /></section><div className="space-y-6 xl:col-span-3"><Card><CardHeader title="Rule Definition" subtitle={selected?.name || 'Select a business rule'} icon={BookCheck} /><CardBody className="min-h-[10rem] text-sm leading-7 text-slate-600">{selected ? <><p><b className="text-slate-900">Rule:</b> {selected.name}</p><p><b className="text-slate-900">Value:</b> {selected.value || selected.description || 'Configured value'}</p><p><b className="text-slate-900">Module:</b> {selected.category || 'System'}</p><p className="mt-3 rounded-xl border border-brand-100 bg-brand-50 p-3">Rule content, related module, active status, and version history are displayed here.</p></> : <p>Select a rule from the list.</p>}</CardBody></Card><section><div className="mb-3"><h2 className="flex items-center gap-2 font-bold text-slate-900"><History size={17} />Audit Traceability</h2><p className="text-xs text-slate-500">Actor, timestamp, previous value, new value, and recorded decision.</p></div><DataTable dense rows={auditRows} empty={{ title: 'No audit events found' }} columns={[{ key: 'actor', header: 'Actor' }, { key: 'timestamp', header: 'Timestamp' }, { key: 'oldValue', header: 'Old Value' }, { key: 'newValue', header: 'New Value' }, { key: 'decision', header: 'Decision' }]} /></section></div></div><div className="mt-6 rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs text-slate-500 shadow-card">3.11.2 Maintain Business Rules and Audit Traceability · rule definitions and audit events are read from policy and monitoring services</div></div>
}
